services:
- docker
env:
  # need to update the matrix below for new Docker images
  # it must have the following conventions name matching of directories:
  # $IMG_REPO/$IMG_TAG
  matrix:
  - IMG_REPO=packer IMG_TAG=latest
  - IMG_REPO=angular-cli IMG_TAG=latest
  - IMG_REPO=create-react-app IMG_TAG=latest
  - IMG_REPO=node-ruby IMG_TAG=latest
  - IMG_REPO=aws-cli IMG_TAG=latest
  global:
  - CI_BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
before_script:
- export DOCKER_PATH=$IMG_REPO/$IMG_TAG
- export CI_REGISTRY_IMAGE=$DOCKER_USER/${IMG_REPO_PREFIX}$IMG_REPO
- export DOCKER_IMAGE=$CI_REGISTRY_IMAGE:$IMG_TAG
script:
- docker build --build-arg CI_BUILD_ID=$TRAVIS_BUILD_ID --build-arg
  CI_BUILD_REF=$TRAVIS_COMMIT --build-arg CI_BUILD_REF_NAME=$DOCKER_PATH --build-arg
  CI_BUILD_TIME=$CI_BUILD_TIME --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE --build-arg
  CI_PROJECT_NAME=$TRAVIS_REPO_SLUG --pull -t $DOCKER_IMAGE $DOCKER_PATH
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push $DOCKER_IMAGE;
  fi
